import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./component/navbar";

export const metadata: Metadata = {
  title: "Tehseen's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head><link rel="icon" href="/icon.png" /></head>
      <body
        
      >
        <Navbar/> {children}
      </body>
    </html>
  );
}
